In [59]:
import numpy as np

In [60]:
a=np.array([
    [1,6012],
    [2,7079],
    [3,6886],
    [4,7230],
    [5,4539],
    [6,5504],
    [7,6971],
    [8,7763],
    [9,8032],
    [10,9569]
])

In [68]:
a

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6539],
       [    6,  7504],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [69]:
a=a+[0,200]

In [70]:
a

array([[    1,  8212],
       [    2,  9279],
       [    3,  9086],
       [    4,  9430],
       [    5,  6739],
       [    6,  7704],
       [    7,  9171],
       [    8,  9963],
       [    9, 10232],
       [   10, 11769]])

In [71]:
a[:,1]>900

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])