In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
a=pd.read_csv("dataset/data_cancer.csv")

In [5]:
a

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [6]:
a.drop(columns=["Unnamed: 32"],inplace=True)

In [7]:
x=a.drop(columns=["diagnosis"])

In [8]:
x

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302        17.99         10.38          122.80     1001.0   
1      842517        20.57         17.77          132.90     1326.0   
2    84300903        19.69         21.25          130.00     1203.0   
3    84348301        11.42         20.38           77.58      386.1   
4    84358402        20.29         14.34          135.10     1297.0   
..        ...          ...           ...             ...        ...   
564    926424        21.56         22.39          142.00     1479.0   
565    926682        20.13         28.25          131.20     1261.0   
566    926954        16.60         28.08          108.30      858.1   
567    927241        20.60         29.33          140.10     1265.0   
568     92751         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0           0.2419  ...        25.380          17.33           184.60   
1           0.1812  ...        24.990          23.41           158.80   
2           0.2069  ...        23.570          25.53           152.50   
3           0.2597  ...        14.910          26.50            98.87   
4           0.1809  ...        22.540          16.67           152.20   
..             ...  ...           ...            ...              ...   
564         0.1726  ...        25.450          26.40           166.10   
565         0.1752  ...        23.690          38.25           155.00   
566         0.1590  ...        18.980          34.12           126.70   
567         0.2397  ...        25.740          39.42           184.60   
568         0.1587  ...         9.456          30.37            59.16   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0        2019.0           0.16220            0.66560           0.7119   
1        1956.0           0.12380            0.18660           0.2416   
2        1709.0           0.14440            0.42450           0.4504   
3         567.7           0.20980            0.86630           0.6869   
4        1575.0           0.13740            0.20500           0.4000   
..          ...               ...                ...              ...   
564      2027.0           0.14100            0.21130           0.4107   
565      1731.0           0.11660            0.19220           0.3215   
566      1124.0           0.11390            0.30940           0.3403   
567      1821.0           0.16500            0.86810           0.9387   
568       268.6           0.08996            0.06444           0.0000   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
0                  0.2654          0.4601                  0.11890  
1                  0.1860          0.2750                  0.08902  
2                  0.2430          0.3613                  0.08758  
3                  0.2575          0.6638                  0.17300  
4                  0.1625          0.2364                  0.07678  
..                    ...             ...

In [9]:
y=a[["diagnosis"]]

In [10]:
y

diagnosis
0           M
1           M
2           M
3           M
4           M
..        ...
564         M
565         M
566         M
567         M
568         B

[569 rows x 1 columns]

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
new=LabelEncoder()

In [13]:
y=new.fit_transform(y)

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [14]:
from sklearn.model_selection import train_test_split

In [15]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=0,test_size=0.2)

In [16]:
xtrain

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
338     897880       10.050         17.53           64.41      310.8   
427      90745       10.800         21.98           68.79      359.9   
406     905189       16.140         14.86          104.30      800.0   
96       86211       12.180         17.84           77.79      451.1   
490   91376701       12.250         22.44           78.18      466.5   
..         ...          ...           ...             ...        ...   
277    8911670       18.810         19.98          120.90     1102.0   
9     84501001       12.460         24.04           83.97      475.9   
359  901034301        9.436         18.32           59.82      278.6   
192     875099        9.720         18.22           60.73      288.1   
559     925291       11.510         23.93           74.52      403.5   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
338          0.10070           0.07326         0.02511              0.01775   
427          0.08801           0.05743         0.03614              0.01404   
406          0.09495           0.08501         0.05500              0.04528   
96           0.10450           0.07057         0.02490              0.02941   
490          0.08192           0.05200         0.01714              0.01261   
..               ...               ...             ...                  ...   
277          0.08923           0.05884         0.08020              0.05843   
9            0.11860           0.23960         0.22730              0.08543   
359          0.10090           0.05956         0.02710              0.01406   
192          0.06950           0.02344         0.00000              0.00000   
559          0.09261           0.10210         0.11120              0.04105   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
338         0.1890  ...        11.160          26.84            71.98   
427         0.2016  ...        12.760          32.04            83.69   
406         0.1735  ...        17.710          19.58           115.90   
96          0.1900  ...        12.830          20.92            82.14   
490         0.1544  ...        14.170          31.99            92.74   
..             ...  ...           ...            ...              ...   
277         0.1550  ...        19.960          24.30           129.00   
9           0.2030  ...        15.090          40.68            97.65   
359         0.1506  ...        12.020          25.02            75.79   
192         0.1653  ...         9.968          20.83            62.25   
559         0.1388  ...        12.480          37.16            82.28   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
338       384.0           0.14020            0.14020           0.1055   
427       489.5           0.13030            0.16960           0.1927   
406       947.9           0.12060            0.17220           0.2310   
96        495.2           0.11400            0.09358           0.0498   
490       622.9           0.12560            0.18040           0.1230   
..          ...               ...                ...              ...   
277      1236.0           0.12430            0.11600           0.2210   
9         711.4           0.18530            1.05800           1.1050   
359       439.6           0.13330            0.10490           0.1144   
192       303.8           0.07117            0.02729           0.0000   
559       474.2           0.12980            0.25170           0.3630   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
338               0.06499          0.2894                  0.07664  
427               0.07485          0.2965                  0.07662  
406               0.11290          0.2778                  0.07012  
96                0.05882          0.2227                  0.07376  
490               0.06335          0.3100                  0.08203  
..                    ...     

In [17]:
xtest

id  radius_mean  texture_mean  perimeter_mean  area_mean  \
512     915691        13.40         20.52           88.64      556.7   
457    9112367        13.21         25.25           84.10      537.9   
439     909410        14.02         15.66           89.59      606.5   
298     892214        14.26         18.17           91.22      633.1   
37      854941        13.03         18.42           82.61      523.8   
..         ...          ...           ...             ...        ...   
213  881094802        17.42         25.56          114.50      948.0   
519     917080        12.75         16.70           82.51      493.8   
432     908194        20.18         19.54          133.80     1250.0   
516     916799        18.31         20.58          120.80     1052.0   
500     914862        15.04         16.74           98.73      689.4   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
512          0.11060           0.14690         0.14450              0.08172   
457          0.08791           0.05205         0.02772              0.02068   
439          0.07966           0.05581         0.02087              0.02652   
298          0.06576           0.05220         0.02475              0.01374   
37           0.08983           0.03766         0.02562              0.02923   
..               ...               ...             ...                  ...   
213          0.10060           0.11460         0.16820              0.06597   
519          0.11250           0.11170         0.03880              0.02995   
432          0.11330           0.14890         0.21330              0.12590   
516          0.10680           0.12480         0.15690              0.09451   
500          0.09883           0.13640         0.07721              0.06142   

     symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
512         0.2116  ...         16.41          29.66           113.30   
457         0.1619  ...         14.35          34.23            91.29   
439         0.1589  ...         14.91          19.31            96.53   
298         0.1635  ...         16.22          25.26           105.80   
37          0.1467  ...         13.30          22.81            84.46   
..             ...  ...           ...            ...              ...   
213         0.1308  ...         18.07          28.07           120.40   
519         0.2120  ...         14.45          21.74            93.63   
432         0.1724  ...         22.03          25.07           146.00   
516         0.1860  ...         21.86          26.20           142.20   
500         0.1668  ...         16.76          20.43           109.70   

     area_worst  smoothness_worst  compactness_worst  concavity_worst  \
512       844.4           0.15740            0.38560          0.51060   
457       632.9           0.12890            0.10630          0.13900   
439       688.9           0.10340            0.10170          0.06260   
298       819.7           0.09445            0.21670          0.15650   
37        545.9           0.09701            0.04619          0.04833   
..          ...               ...                ...              ...   
213      1021.0           0.12430            0.17930          0.28030   
519       624.1           0.14750            0.19790          0.14230   
432      1479.0           0.16650            0.29420          0.53080   
516      1493.0           0.14920            0.25360          0.37590   
500       856.9           0.11350            0.21760          0.18560   

     concave points_worst  symmetry_worst  fractal_dimension_worst  
512               0.20510          0.3585                  0.11090  
457               0.06005          0.2444                  0.06788  
439               0.08216          0.2136                  0.06710  
298               0.07530          0.2636                  0.07676  
37                0.05013          0.1987                  0.06169  
..                    ...     

In [18]:
ytrain

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,

In [19]:
ytest

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0])

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
new=RandomForestClassifier(n_estimators=100)

In [22]:
new.fit(xtrain,ytrain)

RandomForestClassifier()

In [23]:
pred=new.predict(xtest)

In [24]:
pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0])

In [25]:
ytest

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0])

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
accuracy_score(ytest,pred)

0.956140350877193

In [28]:
new1=RandomForestClassifier(n_estimators=100,max_depth=10,max_features=20,random_state=0,max_samples=10)

In [29]:
new1.fit(xtrain,ytrain)

RandomForestClassifier(max_depth=10, max_features=20, max_samples=10,
                       random_state=0)

In [30]:
pred=new.predict(xtest)

In [31]:
pred

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0])

In [32]:
ytest

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0])

In [33]:
from sklearn.metrics import accuracy_score

In [34]:
accuracy_score(ytest,pred)

0.956140350877193

In [35]:
params={
    "max_depth":[12,45,67,15],
    "max_features":[12,34,25,32],
    "max_samples":[23,34,45,56],
    "n_estimators":[100,200,300,None]
}

In [36]:
params

{'max_depth': [12, 45, 67, 15],
 'max_features': [12, 34, 25, 32],
 'max_samples': [23, 34, 45, 56],
 'n_estimators': [100, 200, 300, None]}

In [45]:
new=RandomForestClassifier()

In [49]:
from sklearn.model_selection import GridSearchCV
rf_grid = GridSearchCV(estimator = new,
                       param_grid = params,
                       cv = 6,
                       verbose=2,
                       n_jobs=-1)

In [50]:
grid.fit(xtrain,ytrain)

Fitting 5 folds for each of 256 candidates, totalling 1280 fits


C:\Users\Hp\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
800 fits failed out of a total of 1280.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
320 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Hp\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Hp\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 392, in fit
    self._validate_estimator()
  File "C:\Users\Hp\anaconda3\lib\site-packages\sklearn\ensemble\_base.py", line 131, in _validate_estimator
    raise ValueError(
ValueError: n_estimators must be an integer, got <class

GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [12, 45, 67, 15],
                         'max_features': [12, 34, 25, 32],
                         'max_samples': [23, 34, 45, 56],
                         'n_estimators': [100, 200, 300, None]},
             scoring='accuracy', verbose=2)

In [41]:
grid.best_score_

0.9538461538461538

In [42]:
grid.best_score_

0.9538461538461538