In [191]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [192]:
a=pd.read_csv("dataset/cie_see.csv")

In [193]:
a

Reg No                           Name  Sem  CIE  SEE
0   393CS18001  ABHISHEK NEELKANTAPPA JAMBAGI    1  121  204
1   393CS18002                AISHWARYA PATIL    1  296  440
2   393CS18003     AKASH BASAVARAJ MALAPPAGOL    1  185  308
3   393CS18004   AKASH MUTTAPPA JANGAMASHETTI    1   94  154
4   393CS18005                 ANUSHREE PATIL    1   99  164
5   393CS18007                 CHAITRA PATTAR    1  390  531
6   393CS18008                CHETAN KAPPARAD    1  222  344
7   393CS18010             MALLIKARJUN KORWAR    1  155  267
8   393CS18012            MRUTUNJAY GUDDODAGI    1  193  299
9   393CS18013             NADAF SOHAIL NASIM    1  340  484
10  393CS18014             NIKIL NADUVINAKERI    1   30   54
11  393CS18015            PATIL AMRUTA ARVIND    1  306  450
12  393CS18016      PRASHANT LAKKANNA BAGAYAT    1  228  341
13  393CS18017         PRATHAM LILADHAR NAYAK    1  100  172
14  393CS18018        PRATIBHA SHIVAJI SHINDE    1  138  243
15  393CS18019              RAKSHITA KULKARNI    1  180  304
16  393CS18020     RAVIKUMAR DANAYYA HIREMATH    1   66  130
17  393CS18021             SANTOSH ANDANIMATH    1  118  227
18  393CS18022          SHASHANKGOUDA S PATIL    1  103  177
19  393CS18023             SHRIDHAR NAGESHRAO    1  105  182
20  393CS18024            SHRIKANT S BABALADI    1  280  411
21  393CS18025            SRUSHTI SURESH KORI    1  192  298
22  393CS18026               SUMIT BABU KOLAR    1  245  380
23  393CS18027          SWATI SHIVANAND HUNUR    1  276  420
24  393CS18028         TAMBE GANESH DHONDIRAM    1  377  522
25  393CS18029               TRIMURTI DEGINAL    1  104  180
26  393CS18030         VAISHNAVI HUNASHIKATTI    1  200  327

In [194]:
x=a.iloc[:,3:4]

In [195]:
x

CIE
0   121
1   296
2   185
3    94
4    99
5   390
6   222
7   155
8   193
9   340
10   30
11  306
12  228
13  100
14  138
15  180
16   66
17  118
18  103
19  105
20  280
21  192
22  245
23  276
24  377
25  104
26  200

In [196]:
y=a.iloc[:,4:5]

In [197]:
y

SEE
0   204
1   440
2   308
3   154
4   164
5   531
6   344
7   267
8   299
9   484
10   54
11  450
12  341
13  172
14  243
15  304
16  130
17  227
18  177
19  182
20  411
21  298
22  380
23  420
24  522
25  180
26  327

In [198]:
from sklearn.model_selection import train_test_split

In [199]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=0,test_size=20)

In [200]:
xtrain

CIE
7   155
22  245
3    94
0   121
21  192
15  180
12  228

In [201]:
xtest

CIE
2   185
24  377
14  138
17  118
5   390
11  306
23  276
13  100
19  105
20  280
16   66
1   296
10   30
26  200
25  104
8   193
6   222
4    99
18  103
9   340

In [202]:
ytrain

SEE
7   267
22  380
3   154
0   204
21  298
15  304
12  341

In [203]:
ytest

SEE
2   308
24  522
14  243
17  227
5   531
11  450
23  420
13  172
19  182
20  411
16  130
1   440
10   54
26  327
25  180
8   299
6   344
4   164
18  177
9   484

In [204]:
from sklearn.linear_model import LinearRegression

In [205]:
new=LinearRegression()

In [206]:
new.fit(xtrain,ytrain)

LinearRegression()

In [207]:
pred=new.predict(xtest)

In [208]:
pred

array([[294.39552716],
       [565.04038339],
       [228.14392173],
       [199.9517492 ],
       [583.36529553],
       [464.95817093],
       [422.66991214],
       [174.57879393],
       [181.62683706],
       [428.30834665],
       [126.65210064],
       [450.86208466],
       [ 75.9061901 ],
       [315.53965655],
       [180.21722843],
       [305.67239617],
       [346.55104633],
       [173.1691853 ],
       [178.80761981],
       [512.88486422]])

In [209]:
ytest

SEE
2   308
24  522
14  243
17  227
5   531
11  450
23  420
13  172
19  182
20  411
16  130
1   440
10   54
26  327
25  180
8   299
6   344
4   164
18  177
9   484

In [210]:
new.coef_

array([[1.40960863]])

In [211]:
new.intercept_

array([33.61793131])

In [212]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [213]:
mean_absolute_error(ytest,pred)

14.284086261980837

In [214]:
r2_score(ytest,pred)

0.9792215726904325

In [215]:
q1=mean_squared_error(ytest,pred)
q1

399.12008340275463

In [216]:
np.sqrt(q1)

19.977989974037794

In [217]:
new.score(xtest,ytest)

0.9792215726904325

In [218]:
a=pd.read_csv("dataset/Salary_Data.csv")

In [219]:
a

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.0   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29              5.0  121872

In [220]:
a.isna().sum()

YearsExperience    0
Salary             0
dtype: int64

In [221]:
x=a.iloc[:,0:1]

In [222]:
x

YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.0
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29              5.0

In [223]:
y=a.iloc[:,1:2]

In [224]:
y

Salary
0    39343
1    46205
2    37731
3    43525
4    39891
5    56642
6    60150
7    54445
8    64445
9    57189
10   63218
11   55794
12   56957
13   57081
14   61111
15   67938
16   66029
17   83088
18   81363
19   93940
20   91738
21   98273
22  101302
23  113812
24  109431
25  105582
26  116969
27  112635
28  122391
29  121872

In [225]:
from sklearn.model_selection import train_test_split

In [226]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=0,test_size=0.20)

In [227]:
xtrain

YearsExperience
27              9.6
11              4.0
17              5.3
22              7.9
5               2.9
16              5.1
8               3.2
14              4.5
23              8.2
20              6.8
1               1.3
29              5.0
6               3.0
4               2.2
18              5.9
19              6.0
9               3.7
7               3.2
25              9.0
3               2.0
0               1.1
21              7.1
15              4.0
12              4.0

In [228]:
ytrain

Salary
27  112635
11   55794
17   83088
22  101302
5    56642
16   66029
8    64445
14   61111
23  113812
20   91738
1    46205
29  121872
6    60150
4    39891
18   81363
19   93940
9    57189
7    54445
25  105582
3    43525
0    39343
21   98273
15   67938
12   56957

In [229]:
xtest

YearsExperience
2               1.5
28             10.3
13              4.1
10              3.9
26              9.5
24              8.7

In [230]:
ytest

Salary
2    37731
28  122391
13   57081
10   63218
26  116969
24  109431

In [231]:
from sklearn.linear_model import LinearRegression

In [232]:
new=LinearRegression()

In [233]:
new.fit(xtrain,ytrain)

LinearRegression()

In [234]:
pred=new.predict(xtest)

In [235]:
pred

array([[ 42653.09724913],
       [126152.24991981],
       [ 67323.30144729],
       [ 65425.59343204],
       [118561.41785884],
       [110970.58579787]])

In [236]:
ytest

Salary
2    37731
28  122391
13   57081
10   63218
26  116969
24  109431

In [237]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [238]:
mean_absolute_error(ytest,pred)

4044.207617495724

In [239]:
mean_squared_error(ytest,pred)

25509728.175596107

In [240]:
r2_score(ytest,pred)

0.9764655123831781

In [241]:
new.score(xtest,ytest)

0.9764655123831781

In [242]:
import numpy as np
import pandas as pd

In [243]:
a=pd.read_csv("dataset/cgpapackage.csv")

In [244]:
a

cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [245]:
y=a.iloc[:,1:2]

In [246]:
y

package
0       3.26
1       1.98
2       3.25
3       3.67
4       3.57
..       ...
195     2.46
196     2.57
197     3.24
198     3.96
199     2.33

[200 rows x 1 columns]

In [247]:
x=a.iloc[:,0:1]

In [248]:
x

cgpa
0    6.89
1    5.12
2    7.82
3    7.42
4    6.94
..    ...
195  6.93
196  5.89
197  7.21
198  7.63
199  6.22

[200 rows x 1 columns]

In [249]:
from sklearn.model_selection import train_test_split

In [250]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=0,test_size=0.2)

In [251]:
xtrain

cgpa
134  7.20
66   5.11
26   8.31
113  6.94
168  8.65
..    ...
67   6.51
192  8.25
117  7.12
47   5.84
172  6.93

[160 rows x 1 columns]

In [252]:
xtest

cgpa
18   6.94
170  6.22
107  6.33
98   7.69
177  7.09
182  5.88
5    7.89
146  6.07
12   8.94
152  7.37
61   5.48
125  7.33
180  6.19
154  7.08
80   7.63
7    6.75
33   6.35
130  6.68
37   5.90
74   6.85
183  7.28
145  5.84
45   7.87
159  8.71
60   5.61
123  5.10
179  7.14
185  6.31
122  5.12
44   5.09
16   6.84
55   8.20
150  6.30
111  5.42
22   6.14
189  8.11
129  7.29
4    6.94
83   8.44
106  6.13

In [253]:
ytrain

package
134     2.83
66      1.63
26      3.42
113     2.37
168     3.52
..       ...
67      2.89
192     3.75
117     2.99
47      3.26
172     2.51

[160 rows x 1 columns]

In [254]:
ytest

package
18      2.98
170     2.87
107     2.59
98      3.83
177     3.64
182     2.08
5       2.99
146     2.46
12      3.65
152     3.08
61      1.61
125     3.16
180     2.72
154     2.85
80      3.44
7       2.48
33      2.73
130     2.49
37      2.43
74      3.44
183     2.72
145     2.18
45      3.58
159     4.08
60      2.19
123     2.30
179     3.03
185     3.18
122     2.01
44      1.86
16      2.35
55      3.39
150     2.73
111     2.25
22      2.30
189     4.06
129     3.12
4       3.57
83      3.49
106     2.19

In [255]:
from sklearn.linear_model import LinearRegression

In [256]:
new=LinearRegression()

In [257]:
new.fit(xtrain,ytrain)

LinearRegression()

In [258]:
pred=new.predict(xtest)

In [259]:
pred

array([[2.97012606],
       [2.55516816],
       [2.61856451],
       [3.40237388],
       [3.05657563],
       [2.35921582],
       [3.51763996],
       [2.4687186 ],
       [4.1227869 ],
       [3.21794814],
       [2.12868365],
       [3.19489493],
       [2.53787825],
       [3.05081232],
       [3.36779405],
       [2.86062328],
       [2.63009112],
       [2.82028015],
       [2.37074243],
       [2.91825632],
       [3.1660784 ],
       [2.3361626 ],
       [3.50611335],
       [3.9902309 ],
       [2.20360661],
       [1.90967809],
       [3.08539215],
       [2.6070379 ],
       [1.9212047 ],
       [1.90391479],
       [2.91249302],
       [3.69630239],
       [2.60127459],
       [2.09410383],
       [2.50906173],
       [3.64443265],
       [3.17184171],
       [2.97012606],
       [3.83462169],
       [2.50329842]])

In [260]:
ytest

package
18      2.98
170     2.87
107     2.59
98      3.83
177     3.64
182     2.08
5       2.99
146     2.46
12      3.65
152     3.08
61      1.61
125     3.16
180     2.72
154     2.85
80      3.44
7       2.48
33      2.73
130     2.49
37      2.43
74      3.44
183     2.72
145     2.18
45      3.58
159     4.08
60      2.19
123     2.30
179     3.03
185     3.18
122     2.01
44      1.86
16      2.35
55      3.39
150     2.73
111     2.25
22      2.30
189     4.06
129     3.12
4       3.57
83      3.49
106     2.19

In [261]:
from sklearn.metrics import r2_score

In [262]:
r2_score(ytest,pred)

0.7297167943957027

In [263]:
new.score(xtrain,ytrain)

0.7813227298629095

In [264]:
a=pd.read_csv("dataset/Housing.csv")

In [265]:
a

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [266]:
x=a.iloc[:,1:]

In [267]:
x

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    7420         4          2        3      yes        no       no   
1    8960         4          4        4      yes        no       no   
2    9960         3          2        2      yes        no      yes   
3    7500         4          2        2      yes        no      yes   
4    7420         4          1        2      yes       yes      yes   
..    ...       ...        ...      ...      ...       ...      ...   
540  3000         2          1        1      yes        no      yes   
541  2400         3          1        1       no        no       no   
542  3620         2          1        1      yes        no       no   
543  2910         3          1        1       no        no       no   
544  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 12 columns]

In [268]:
y=a[["price"]]

In [269]:
y

price
0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
..        ...
540   1820000
541   1767150
542   1750000
543   1750000
544   1750000

[545 rows x 1 columns]

In [270]:
from sklearn.model_selection import train_test_split

In [271]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=0,test_size=0.20)

In [272]:
xtrain

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
542   3620         2          1        1      yes        no       no   
496   4000         2          1        1      yes        no       no   
484   3040         2          1        1       no        no       no   
507   3600         2          1        1      yes        no       no   
252   9860         3          1        1      yes        no       no   
..     ...       ...        ...      ...      ...       ...      ...   
70    4000         3          2        2      yes        no      yes   
277  10360         2          1        1      yes        no       no   
9     5750         3          2        4      yes       yes       no   
359   3600         3          1        1      yes        no       no   
192   6600         3          1        1      yes       yes      yes   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
542              no              no        0       no      unfurnished  
496              no              no        0       no      unfurnished  
484              no              no        0       no      unfurnished  
507              no              no        0       no      unfurnished  
252              no              no        0       no   semi-furnished  
..              ...             ...      ...      ...              ...  
70               no             yes        0      yes   semi-furnished  
277              no              no        1      yes   semi-furnished  
9                no             yes        1      yes      unfurnished  
359              no              no        1       no      unfurnished  
192              no              no        0      yes        furnished  

[436 rows x 12 columns]

In [273]:
xtrain.shape

(436, 12)

In [274]:
xtest

area  bedrooms  bathrooms  stories mainroad guestroom basement  \
239   4000         3          1        2      yes        no       no   
113   9620         3          1        1      yes        no      yes   
325   3460         4          1        2      yes        no       no   
66   13200         2          1        1      yes        no      yes   
479   3660         4          1        2       no        no       no   
..     ...       ...        ...      ...      ...       ...      ...   
76    6420         3          2        3      yes        no       no   
132   5200         3          1        3      yes        no       no   
311   6060         2          1        1      yes        no      yes   
464   4500         2          1        2      yes        no       no   
155   6100         3          2        1      yes        no      yes   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
239              no              no        1       no        furnished  
113              no              no        2      yes        furnished  
325              no             yes        0       no   semi-furnished  
66              yes              no        1       no        furnished  
479              no              no        0       no      unfurnished  
..              ...             ...      ...      ...              ...  
76               no             yes        0      yes        furnished  
132              no             yes        0       no   semi-furnished  
311              no              no        1       no   semi-furnished  
464             yes              no        1       no   semi-furnished  
155              no              no        2      yes        furnished  

[109 rows x 12 columns]

In [275]:
xtest.shape

(109, 12)

In [276]:
ytrain

price
542  1750000
496  2695000
484  2870000
507  2590000
252  4515000
..       ...
70   6790000
277  4305000
9    9800000
359  3710000
192  5040000

[436 rows x 1 columns]

In [277]:
ytrain.shape

(436, 1)

In [278]:
ytest

price
239  4585000
113  6083000
325  4007500
66   6930000
479  2940000
..       ...
76   6650000
132  5810000
311  4123000
464  3080000
155  5530000

[109 rows x 1 columns]

In [279]:
ytest.shape

(109, 1)

In [280]:
a.head(2)

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished

In [281]:
a["furnishingstatus"].unique()

array(['furnished', 'semi-furnished', 'unfurnished'], dtype=object)

In [282]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [283]:
new=ColumnTransformer(transformers=[
        ('tr1',OrdinalEncoder(categories=[["furnished","semi-furnished","unfurnished"]]),["furnishingstatus"]),
        ("tr2",OneHotEncoder(sparse=False,drop="first"),["mainroad","guestroom","basement","hotwaterheating","airconditioning","prefarea"])
],remainder="passthrough")

In [284]:
xtest=new.fit_transform(xtest)

In [285]:
xtrain=new.fit_transform(xtrain)

In [286]:
from sklearn.linear_model import LinearRegression

In [287]:
new=LinearRegression()

In [288]:
new.fit(xtrain,ytrain)

LinearRegression()

In [290]:
pred=new.predict(xtest)

In [291]:
pred

array([[ 4019080.69890168],
       [ 6258021.76856349],
       [ 4392719.13411076],
       [ 7335082.21688079],
       [ 2892857.56615672],
       [ 7084655.57701768],
       [ 3258634.73504743],
       [ 3196499.16068636],
       [ 3520106.0113497 ],
       [ 8359610.28845418],
       [ 6646926.36096842],
       [ 3788844.63269259],
       [ 3734072.96468002],
       [ 4616010.40973193],
       [ 3946124.94405776],
       [ 2023177.46846885],
       [ 3975554.48783028],
       [ 3624716.96500876],
       [ 3210282.74216177],
       [ 4668411.38105813],
       [ 5893719.66376469],
       [ 6415683.8380721 ],
       [ 4657036.5583194 ],
       [ 2704096.1120531 ],
       [ 5356909.86181434],
       [ 5740682.5679808 ],
       [ 5337586.47961064],
       [ 5444859.96648232],
       [ 5702144.57144398],
       [ 5865872.30432732],
       [ 3307327.30668426],
       [ 6299491.0268435 ],
       [ 7123479.95544284],
       [ 2960326.86653062],
       [ 4424323.19483826],
       [ 5125081.855

In [292]:
ytest

price
239  4585000
113  6083000
325  4007500
66   6930000
479  2940000
..       ...
76   6650000
132  5810000
311  4123000
464  3080000
155  5530000

[109 rows x 1 columns]

In [293]:
from sklearn.metrics import r2_score

In [294]:
r2_score(ytest,pred)

0.6578047592637695